language: node_js
env:
  global:
    - secure: h+pYHZL1YxQwW4T4IQfQBIAad/AbpzWOwUG0IuItfQxGXR3aBKLiAQRyDv92CVi6hdny93vE8YLb9zCm7VreB9UrVzzZ9pxNc0pB63raMxt6RcL3LzMaqPfucvS0rQxU0HOnUFYK8qne6m8Ss3YXJvt+8fTJch+86HLbwQ5zsXhS+5Noro5Fif+0jLPGuCLGyj7RORtkh9IxTQQAa4ckxttodPqpydCjPPsDKW2j2p2FXA9TpaJDEdw9igPvJIbPYT4fTcd9KCK0ZIZFHyEG2VuxTeJD4fNTRC0ce5UQzU9CinSeqdyq9NDxO/hHcOEfcz1gWewsnUNkxlX74cnXCfvPkfohBer/D2Tw1N9zqZdwcl98QMU/gmqNBTrRZ4tIut/mR4NQL8Z/pNNIY6MvyqG+7YesapyNgfokfLtpCaIQQDun+sB1TR6+K1WkZzeeYYy5qDhrSSqUBfXd5G/PmEDovIVhvOhD4b9hCJOK5GT8RVZiAzmzn/ul5o+5dpZT5uWpffh85bssz4CBnKNne7qvb47/1h9SntkaA1zuEYpFjKcqrhQacmHT5fPAtcJWqWj05iMHwc/vuELH0bEkIdcxcM2HN1QwbcLPXN+654D9ms0ZdHQjVpV0MyRUo/34U8oapBLqUaM0IlNvXtT8eCkoXshi+9ep4rauHvHe+Is=
node_js:
  - '10'
sudo: false
script:
  - npm test
  - npm run build
deploy:
  provider: script
  script: scripts/trigger-rokka-build.sh
  on:
    branch: master
